### ISSUE TITLE
opengl golang apps

### ISSUE THREAD

**Issue by joeblew99** [johnsiilver/boutique#2]
this looks like a perfect match for opengl based apps that work on desktop, mobile.

I can try to make a little demo if you want.

Or here are the libs

https://github.com/aarzilli/nucular
- golang forms based apps with huge concurreny.
- i woudl try this one first for the stock demo.

https://github.com/xlab/android-go
https://github.com/xlab/ios-go
- you can get the nucular stuff working on android & ios using this.
- It does not use gomobile but is mouch more low level and better because of it.

https://github.com/hajimehoshi/ebiten/tree/master/internal/opengl
- there is also a way to make it work on web using gopherjs and webgl

---

All of these us just opengl essentially and so makes it nice with your lib because you have direct control and its all golang and nothing else.

If you want we can get a demo of the stock tracker working on all 3.
Let me know :)

**Comment by johnsiilver** [comment]
Hey Joe,

Sounds like a great demo.  I'd love for you to give it a try instead of me, if you have the time, for the main reason that it gives some third-party usage, which helps to verify the design.

If your out at gophercon, we can meetup and talk about it.  

Cheers!

**Comment by joeblew99** [comment]
Denver is too far or me. I am in Berlin.

Am playing around with you lib with QT.
This is the basis "shell" i use:
https://github.com/therecipe/qt/tree/master/internal/examples/qml/drawer_nav_x

Will see how well your thing works with this....  Because your thing embraces immutable it "should" work well. 
Just started so not sure yet.

If you want to follwo along i will make a repo...

**Comment by johnsiilver** [comment]
There were so many people from Europe figured there was a chance you were in town.  

Let me know the rough spots you find.  I'm still not 100% sure that this provides the easiest method to do these things.  I like problems where you can't be sure if the solution is better until you try it for a bit.  This may be successful or might just be too heavy handed.

One of the things I might try to add later is some type of compiler intermediary that uses the AST to discover if immutability is being honored.  I'd probably use $ as a symbol on a passed variable to indicate immutability.  I'm not 100% sure if it can be done (or that I have enough grasp of the AST to be able to do it).  The intermediary, if not problems were found, would strip the $ from the type and send it to the compiler.

I would find that useful not only here, but in other software.  

In the meantime, I'm working on something else that uses this lib, we'll see how that goes.

Cheers!

**Comment by joeblew99** [comment]
yeah i am also not sure how well it will work. Just playing really.
Also trying it out with golang and opengl
- https://github.com/walesey/go-engine is the basis
- It uses an emitter   and listeners and handlers. A bit different from signal.
  - https://github.com/walesey/go-engine/blob/master/emitter/emitter.go


compile time checking for immutability is nice for sure. Not sure its that important but would be when code bases get large for people.

The golib thingy looks really interesting.  I can see your taking a very different path from other ways of doing these types of things. Nice to see.

**Comment by johnsiilver** [comment]
I'm not sure what I'm doing exactly that is different in golib, but I'm glad you like it.  

Yeah, the compile time checking isn't important for this all that much.  But I think it is something golang will get as a language feature at some point.  If I could do it, would prove it was possible.  But its a nice to have and at this point, my plate is overflowing.

Check back when you got something working, find something broken, or whatever the next state is.

Cheers.

**Comment by johnsiilver** [comment]
Make note that I did find a bug that I just fixed in version: v0.1.1-beta.1

**Comment by joeblew99** [comment]
cheers. Will close this out now. Will report an issues as i find them.
